#!/usr/bin/env bash

# Download and install required bash library framework if not installed
if [[ -z "${BASH_SCRIPT_PATH+x}" ]]; then
  echo "Downloading required framework..."
  source <(curl -s https://raw.githubusercontent.com/moep/shellscripts/master/install) 
  echo
  echo "Please restart you shell in order to activate the changes!"
  echo "Afterwards run install again."
  exit 0
fi

# TODO support profiles (desktop (light / normal), server)
trap on_ctrl_c INT

source "${BASH_SCRIPT_PATH}/bootstrap.sh"

include lib/cli.sh
include lib/core.sh
include lib/os.sh
include lib/str.sh
include lib/ui.sh

include lib/osx/iterm2.sh
# Project specific include(s)
loader_addpath "$(dirname "${BASH_SOURCE[0]}")"
include src/dotfiles.sh
bootstrap::finish

REQUIRED_PGMS=()

declare -r K_ICON_CHECK='✓'
declare -r K_ICON_WARN='⚠'
declare -r K_ICON_FAIL='✘'

declare ARG_SYMLINK=true
declare ARG_BATCH=false

function main {
  parse_args $* || usage

  ansi::cls
  ansi::cur_pos 1 1
  ansi::cur_hide
  cat banner.txt
  ansi::reset

  core::assert_available ${REQUIRED_PGMS[@]}
  if [[ $ARG_BATCH == "true" ]]; then
    function cli::prompt_yn {
      local preselection=$2
      if ! is::_ empty "${preselection}"; then
        case $preselection in
          'y'|'Y')
            return $TRUE
          ;;
          *)
            return $FALSE
          ;;
        esac
      else
        return $TRUE
      fi
    }
  fi

  echo
  ansi::bold; str::pad_right 15 "OS:"; ansi::reset; printf "%s" "$(uname -spr)"; printf "\r\n"
  ansi::bold; str::pad_right 15 "Symlink:"; ansi::reset; echo $ARG_SYMLINK
  ansi::bold; str::pad_right 15 "Batch mode:"; ansi::reset; echo $ARG_BATCH
  echo 
  
  # Theme selection
  #dotfiles::select_tty_theme
  
  # Install programms needed for this script
  ui::h1 prerequisites
  dotfiles::install_prerequisites

  # Copy Dotfiles
  dotfiles::copy_dotfiles
  
  # Install Vim Plugins
  ui::h1 plugins
  cli::prompt_yn "Install vim plugins?" y && {
    dotfiles::install_vim_plugins
    echo
  }

  ansi::cur_show
}

function parse_args() {
  for arg in "$@"; do
    case $arg in
      -b|--batch)
        ARG_BATCH=true
        ;;
      -s|--no-symlink)
        ARG_SYMLINK=false
      ;;
      *)
        usage
    esac
  done

  return 0
}

function usage() {
  echo $(ansi::bold)"Usage: "$(ansi::reset)$(basename $0) $(ansi::white)"(args)"$(ansi::reset)
  #echo "  "$(ansi::bold)"-b --batch"$(ansi::reset)"         Batch mode"
  echo "  "$(ansi::bold)"-s --no-symlink"$(ansi::reset)"    Copy Files instead of symlinking"
  echo "  "$(ansi::bold)"-? -h --help"$(ansi::reset)"       Show Help"
  exit 1
}

function on_ctrl_c() {
  cleanup
  echo
  echo "Aborted."

  exit 0
}

function cleanup() {
  ansi::cur_show
  ansi::reset
  ui::enable_keyboard_input
  # Kill all child processes
  pkill -P $$

  echo
}

main $@ 

