# Automatically created
background='#0000a4'
black='4f4f4f'
red='ff6c60'
green='a8ff60'
yellow='ffffb6'
blue='96cbfe'
magenta='ff73fd'
cyan='c6c5fe'
white='eeeeee'
brightBlack='7c7c7c'
brightRed='ffb6b0'
brightGreen='ceffac'
brightYellow='ffffcc'
brightBlue='b5dcff'
brightMagenta='ff9cfe'
brightCyan='dfdffe'
brightWhite='ffffff'
