# Automatically created
background='#000000'
black='4f4f4f'
red='fa6c60'
green='a8ff60'
yellow='fffeb7'
blue='96cafe'
magenta='fa73fd'
cyan='c6c5fe'
white='efedef'
brightBlack='7b7b7b'
brightRed='fcb6b0'
brightGreen='cfffab'
brightYellow='ffffcc'
brightBlue='b5dcff'
brightMagenta='fb9cfe'
brightCyan='e0e0fe'
brightWhite='ffffff'
