# Automatically created
background='#002451'
black='000000'
red='ff9da4'
green='d1f1a9'
yellow='ffeead'
blue='bbdaff'
magenta='ebbbff'
cyan='99ffff'
white='ffffff'
brightBlack='000000'
brightRed='ff9da4'
brightGreen='d1f1a9'
brightYellow='ffeead'
brightBlue='bbdaff'
brightMagenta='ebbbff'
brightCyan='99ffff'
brightWhite='ffffff'
